# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
# BASED ON c:\Users\Jack\Projects\MASA\STM32-Testing\stm32_nucleo_h723zg_tcp

function(add_st_target_properties TARGET_NAME)

target_compile_definitions(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:STM32H723xx>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:STM32H723xx>"
)

target_include_directories(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32H7xx_HAL_Driver\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32H7xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32H7xx\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/LWIP\\App>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/LWIP\\Target>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\system>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\FreeRTOS\\Source\\include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\FreeRTOS\\Source\\CMSIS_RTOS_V2>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\FreeRTOS\\Source\\portable\\GCC\\ARM_CM4F>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\BSP\\Components\\lan8742>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\netif\\ppp>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\lwip>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\lwip\\apps>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\lwip\\priv>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\lwip\\prot>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\netif>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\compat\\posix>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\compat\\posix\\arpa>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\compat\\posix\\net>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\compat\\posix\\sys>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\compat\\stdc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\system\\arch>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32H7xx_HAL_Driver\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32H7xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32H7xx\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/LWIP\\App>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/LWIP\\Target>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\system>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\FreeRTOS\\Source\\include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\FreeRTOS\\Source\\CMSIS_RTOS_V2>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\FreeRTOS\\Source\\portable\\GCC\\ARM_CM4F>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\BSP\\Components\\lan8742>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\netif\\ppp>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\lwip>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\lwip\\apps>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\lwip\\priv>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\lwip\\prot>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\netif>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\compat\\posix>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\compat\\posix\\arpa>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\compat\\posix\\net>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\compat\\posix\\sys>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\src\\include\\compat\\stdc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\LwIP\\system\\arch>"
)

target_compile_options(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:-g3>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:ASM>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-g0>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-O2>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-Os>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-Os>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<CONFIG:Debug>:-mcpu=cortex-m7>"
    "$<$<CONFIG:Debug>:-mfpu=fpv5-d16>"
    "$<$<CONFIG:Debug>:-mfloat-abi=hard>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m7>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv5-d16>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
)

target_link_libraries(
    ${TARGET_NAME} PRIVATE
)

target_link_directories(
    ${TARGET_NAME} PRIVATE
)

target_link_options(
    ${TARGET_NAME} PRIVATE
    "$<$<CONFIG:Debug>:-mcpu=cortex-m7>"
    "$<$<CONFIG:Debug>:-mfpu=fpv5-d16>"
    "$<$<CONFIG:Debug>:-mfloat-abi=hard>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m7>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv5-d16>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
    -T
    "$<$<CONFIG:Debug>:${PROJECT_SOURCE_DIR}/STM32H723ZGTX_FLASH.ld>"
    "$<$<NOT:$<CONFIG:Debug>>:${PROJECT_SOURCE_DIR}/STM32H723ZGTX_FLASH.ld>"
)

target_sources(
    ${TARGET_NAME} PRIVATE
    "Core\\Src\\freertos.c"
    "Core\\Src\\lwiperf.c"
    "Core\\Src\\main.c"
    "Core\\Src\\stm32h7xx_hal_msp.c"
    "Core\\Src\\stm32h7xx_hal_timebase_tim.c"
    "Core\\Src\\stm32h7xx_it.c"
    "Core\\Src\\syscalls.c"
    "Core\\Src\\sysmem.c"
    "Core\\Src\\system_stm32h7xx.c"
    "Core\\Startup\\startup_stm32h723zgtx.s"
    "Middlewares\\Third_Party\\FreeRTOS\\Source\\CMSIS_RTOS_V2\\cmsis_os2.c"
    "Middlewares\\Third_Party\\FreeRTOS\\Source\\croutine.c"
    "Middlewares\\Third_Party\\FreeRTOS\\Source\\event_groups.c"
    "Middlewares\\Third_Party\\FreeRTOS\\Source\\list.c"
    "Middlewares\\Third_Party\\FreeRTOS\\Source\\portable\\GCC\\ARM_CM4F\\port.c"
    "Middlewares\\Third_Party\\FreeRTOS\\Source\\portable\\MemMang\\heap_4.c"
    "Middlewares\\Third_Party\\FreeRTOS\\Source\\queue.c"
    "Middlewares\\Third_Party\\FreeRTOS\\Source\\stream_buffer.c"
    "Middlewares\\Third_Party\\FreeRTOS\\Source\\tasks.c"
    "Middlewares\\Third_Party\\FreeRTOS\\Source\\timers.c"
    "Middlewares\\Third_Party\\LwIP\\src\\api\\api_lib.c"
    "Middlewares\\Third_Party\\LwIP\\src\\api\\api_msg.c"
    "Middlewares\\Third_Party\\LwIP\\src\\api\\err.c"
    "Middlewares\\Third_Party\\LwIP\\src\\api\\if_api.c"
    "Middlewares\\Third_Party\\LwIP\\src\\api\\netbuf.c"
    "Middlewares\\Third_Party\\LwIP\\src\\api\\netdb.c"
    "Middlewares\\Third_Party\\LwIP\\src\\api\\netifapi.c"
    "Middlewares\\Third_Party\\LwIP\\src\\api\\sockets.c"
    "Middlewares\\Third_Party\\LwIP\\src\\api\\tcpip.c"
    "Middlewares\\Third_Party\\LwIP\\src\\apps\\mqtt\\mqtt.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\altcp_alloc.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\altcp_tcp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\altcp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\def.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\dns.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\inet_chksum.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\init.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ip.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv4\\autoip.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv4\\dhcp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv4\\etharp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv4\\icmp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv4\\igmp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv4\\ip4_addr.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv4\\ip4_frag.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv4\\ip4.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv6\\dhcp6.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv6\\ethip6.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv6\\icmp6.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv6\\inet6.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv6\\ip6_addr.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv6\\ip6_frag.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv6\\ip6.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv6\\mld6.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\ipv6\\nd6.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\mem.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\memp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\netif.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\pbuf.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\raw.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\stats.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\sys.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\tcp_in.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\tcp_out.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\tcp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\timeouts.c"
    "Middlewares\\Third_Party\\LwIP\\src\\core\\udp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\bridgeif_fdb.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\bridgeif.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ethernet.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\lowpan6_ble.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\lowpan6_common.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\lowpan6.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\auth.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\ccp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\chap_ms.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\chap-md5.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\chap-new.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\demand.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\eap.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\ecp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\eui64.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\fsm.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\ipcp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\ipv6cp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\lcp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\magic.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\mppe.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\multilink.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\ppp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\pppapi.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\pppcrypt.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\pppoe.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\pppol2tp.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\pppos.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\upap.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\utils.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\ppp\\vj.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\slipif.c"
    "Middlewares\\Third_Party\\LwIP\\src\\netif\\zepif.c"
    "Middlewares\\Third_Party\\LwIP\\system\\OS\\sys_arch.c"
    "LWIP\\App\\lwip.c"
    "LWIP\\Target\\ethernetif.c"
    "Drivers\\BSP\\Components\\lan8742\\lan8742.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_cortex.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_dma_ex.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_dma.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_eth_ex.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_eth.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_exti.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_flash_ex.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_flash.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_gpio.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_hsem.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_i2c_ex.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_i2c.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_mdma.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_pwr_ex.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_pwr.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_rcc_ex.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_rcc.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_tim_ex.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal_tim.c"
    "Drivers\\STM32H7xx_HAL_Driver\\Src\\stm32h7xx_hal.c"
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_SIZE} $<TARGET_FILE:${TARGET_NAME}>
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O ihex
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.hex
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O binary
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.bin
)

endfunction()